### ISSUE TITLE
Sky in Dragon Crown of Karaz Quest is Tzeentchish

### ISSUE THREAD

**Issue by Murthor** [chadvandy/cbfm_wh3#1097]
**Describe the bug**
The Sky/Atmosphere in the Quest battle called "Dragon Crown of Karaz"  is bugged, its all Tzeentch like instead of how it should be.

**Expected behavior**
The sky should be cloudy and normal looking, like the other quest battles that take place in the same location for Empire and Greenskins.

**To Reproduce**
1. Play as the Dwarfs as Thorgrim
2. Play the Quest battle, either from the campaign or from the quest battles page
3. Notice the Sky/Atmosphere of the map is all Tzeentch influenced.

**Screenshots**
![20230612144817_1](https://github.com/chadvandy/cbfm_wh3/assets/52479032/1454b522-d934-424d-8aa1-545c186e5f4f)

![20230612144822_1](https://github.com/chadvandy/cbfm_wh3/assets/52479032/31e82efe-3497-40be-a53d-3311a9d06723)

![20230612144802_1](https://github.com/chadvandy/cbfm_wh3/assets/52479032/41284d81-10ad-409c-9435-94380399f4a5)

**Comment by Drazhir2** [comment]
can confirm, sky is very dwarf unfriendly in this quest battle.

fixed by changing environments.csv from wh_tze_realm_09 to wh_day_storm_01, it is quite bright and sunny, not sure how it is supposed to look but that was the environment override already present in the map folder.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b9e3aa1a-77a1-457f-b1dc-79a38101024d)

here's the pack file (rename to .pack due to upload restrictions).
[zzz_cbfm_qb_blackfirepass.patch](https://github.com/chadvandy/cbfm_wh3/files/11747751/zzz_cbfm_qb_blackfirepass.patch)

**Comment by Murthor** [comment]
Where do I put the fix at?

**Comment by Drazhir2** [comment]
just install the cbfm mod, the fix has been pushed to it.

**Comment by Murthor** [comment]
I figured it out, but the official mod just makes the sky clear, stormy is better so I downloaded your file and enabled it.

**Comment by Drazhir2** [comment]
the official mod has the same fix in it, maybe your steam hasn't updated cbfm yet as it has just been pushed, you can try unsubbing/resubbing to the mod to force the update.

**Comment by Murthor** [comment]
I unsubbed and resubbed CBFM, I even turned off all of the mods except for CBFM and the sky is just a clear sky when it should be stormy.  its still nice that the tzeentch stuff is gone, but I think that CBFM might have failed to register the fix.

**Comment by Drazhir2** [comment]
I tested it and you're right, the standalone fix has the correct stormy weather and CBFM has clear sky (which is the default when the game doesn't find the defined weather).

Which is interesting because there's the exact same content in both:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/e7fd0f34-515d-4aa0-a1f4-8bff33971692)

**Comment by Drazhir2** [comment]
They look the same but they aren't actually the same, they have different end of line characters:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/1887f057-93a4-436c-bce8-d7ae31ecbb56)

Obviously the game prefers one type over the other.

**Comment by Drazhir2** [comment]
here is the correct file if someone wants to replace it in cbfm (import it, don't copy/paste the content)
[environments.csv](https://github.com/chadvandy/cbfm_wh3/files/11805223/environments.csv)

**Comment by Drazhir2** [comment]
fixed in 4.2.0
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/79f09b40-c73b-4ce9-bcc7-e6ee0cbfed34)
