### ISSUE TITLE
Oxyotl gets +1% construction time as a "reward" for a vision

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#1151]
![20230625145014_1](https://github.com/chadvandy/cbfm_wh3/assets/54481962/ba714541-4157-4924-ba6c-329c9af46298)

**Comment by Drazhir2** [comment]
Looking at all other such effects they're the only ones with such low values (3% build time won't make a dent in even a 10 turns building) on top of being positive instead of negative:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/80491709-9629-49e2-b9c4-45626ed8e011)

Here is the fix, using the same negative values as the existing wh2_dlc17_threat_map_reward_region_razed_1 effect bundles (as usual, rename to .pack):
[zzz_cbfm_oxyvisionreward.patch](https://github.com/chadvandy/cbfm_wh3/files/11869402/zzz_cbfm_oxyvisionreward.patch)

**Comment by Harmandodelavega** [comment]
Think flat construction time would be better

**Comment by Drazhir2** [comment]
There's very few such effects and they top out at -2, makes a -5 really over the top which is why I went with the safe route.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/44904f80-e8ed-4ae2-ba44-c74e3653ed32)

**Comment by floskan** [comment]
> It's the only thing we could plausibly pass as a bugfix, since it seems the guy just tilted when he saw that siege holdout time didn't exist anymore

Do i make a PR with the supplied pack? Or

**Comment by Harmandodelavega** [comment]
My bad didn't understand there was another identical effect
@floskan go ahead

**Comment by floskan** [comment]
Removed from main
