### ISSUE TITLE
agent campaign movement effects don't work

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/cbfm_wh3#119]
Specifically, those effects dont work as intended - they do nothing for agents/heroes (second one does work for lords though as intended):
wh_main_effect_agent_movement_range_mod
wh_main_effect_force_all_campaign_movement_range

**Comment by FormerDeveloper** [comment]
Yes, I've seen this as well. I reported the same issue here:

https://github.com/chadvandy/cbfm_wh3/issues/80#issue-1360691900

Easiest way to verify this is with the Strategist trait or an item that gives bonus movement range. In either case, campaign map movement stays fixed at 100.

It's been an issue since WH3 launch, but thinking back, hero movement was also a little buggy in the last few patches of WH2, since it wouldn't indicate how much movement it would use when you did a right click preview. And since WH2 didn't report any numbers on movement range, I can't say for certain that heroes were benefitting from movement bonuses back in WH2 either.

**Comment by Harmandodelavega** [comment]
Never worked, there is no effect in the game that works for agents as far as I've looked(a lot)
Mods that buff agent movement always use base movement, no modifier
