### ISSUE TITLE
Loading screen reaches 95% and crashes while loading prologue or campaign

### ISSUE THREAD

**Issue by ArmedTheologian** [chadvandy/cbfm_wh3#1194]
**Describe the bug**
Loading screen reaches 95% and crashes while loading prologue or campaign without fail. Continues after reinstall and several restarts.

**Expected behavior**
I suppose I expected it to finish loading?

**To Reproduce**
1. Load into main screen after start up
2. Select Campaign
3. Select New
4. Select The Lost God
5. Enable Tutorial (Optional)
6. Begin new campaign
7.  Allow loading bar to reach 95%
8. Experience crash/bug

**Screenshots**
N/A

**Saves**
N/A
**Additional context**
I am on the latest build (As far as I know, I just purchased the game on July 2nd, have been troubleshooting since then.)
v3.1.0
20787.2936986

Lastly, thank you all so much for the work you have put into this. Brand new into this community and yall have made me feel at home asap!

**Comment by mfvreeland** [comment]
Are you using any mods (including this one)?

**Comment by ArmedTheologian** [comment]
No I am not. I have tried booting it up both with and without this mod.

**Comment by Drazhir2** [comment]
This sounds like a general "I can't start any campaign" issue. It could come from a few things (your software, your hardware, too low specs to run the game etc...).

Our ability to fix bugs in cbfm is contingent to us reproducing the issue in order to fix it. 

I don't think a cbfm github issue is the place to get support for this, it should be handled in total war discord/forums/SEGA support.

**Comment by mfvreeland** [comment]
Confirmed, cannot reproduce this issue.
