### ISSUE TITLE
Kislev does not get access to the Magic Wards of Climate Change commandment in Bloodfire Falls

### ISSUE THREAD

**Issue by Drazhir2** [chadvandy/cbfm_wh3#1273]
Only the 4 regular commandments show up in that province:
![913i87aqguah](https://github.com/chadvandy/cbfm_wh3/assets/135981276/e3980e55-1cba-48a3-9170-b4582e8d4ae0)

It has only been defined for RoC in the db, combi entries should be added for IE:
![a0boft2pyc5d](https://github.com/chadvandy/cbfm_wh3/assets/135981276/643dfd89-759c-49d3-a76a-86d604f612ff)

**Comment by Drazhir2** [comment]
This might actually be intended. If the commandement is supposed to only show up in provinces where ALL settlements have chaotic climate:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/60a8fc69-33b5-461e-9df1-9893645fb441)

It makes Boris very sad in his starting province.

**Comment by Harmandodelavega** [comment]
I'm guessing it's intended, the anti chaotic edict is ridiculous and would give stuff like instant construction etc.:
wh2_main_effect_building_construction_time_mod_all	region_to_region_own	-100.0000
wh2_main_effect_climate_recruitment_duration_all	region_to_region_own	-1.0000
wh3_main_effect_province_growth_climate	province_to_province_own	7.0000
wh3_main_effect_public_order_climate	region_to_province_own_unseen	3.0000
wh_main_effect_building_construction_cost_mod	region_to_region_own	-50.0000
wh_main_effect_economy_gdp_mod_all	region_to_region_own	50.0000
wh_main_effect_force_all_campaign_replenishment_rate	region_to_force_own	15.0000

**Comment by Drazhir2** [comment]
Not a bug then.

**Comment by czaccardelli** [comment]
This should be re-opened as it's definitely a bug.  Many, many provinces which exist entirely in with Chaotic Wasteland terrain are also not present as DB entries (especially in IE) and also for Katarin and Kostaltyn.  There are provinces which have a DB entry for the ROC campaign but are missing it for IE as well.

Also, this commandment certainly does not grant instant building in Tower of Torment and such.  If this isn't a bug then the edict is basically unusable in IE because it's defined for almost no IE provinces.

**Comment by Harmandodelavega** [comment]
make another issue
