### ISSUE TITLE
Ogre contracts not working/countdown timer for contracts stops working when at 1

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1354]
https://youtu.be/A5QQ9LnT8x4?t=1021

**Comment by Drazhir2** [comment]
Had a look at the issue, it's our old friend get_random_ancillary_key_for_faction that returns nil to the ogre_contract when it's building a payload string.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/561767a3-8cae-425e-ad4d-608104caabfc)

My gut says the issue is probably random but I haven't done much testing after seeing the script break.
