### ISSUE TITLE
WoC Post-Battle Replenishment Only Available For Norscan or Warriors of Chaos Enemies

### ISSUE THREAD

**Issue by DupKan** [chadvandy/cbfm_wh3#1400]
**Describe the bug**
With Patch 4.1 Warrior of Chaos lost the ability to replenish after battle from defeated enemies that aren't either Norscan or Warriors of Chaos factions.

**Expected behavior**
To be able to select the replenishment option after battle.

**To Reproduce**
1. Play as any WoC faction
2. Defeat enemy that isn't a Norscan or Warriors of Chaos faction
3. Unable to select replenishment option

**Comment by DupKan** [comment]
It worked for other factions prior to 4.1 for post-battle replenishment.
You also do not get replenishment when vassaling a faction / gifting to a vassal when capturing a settlement,
Neither of these changes were in patch notes.

**Comment by Drazhir2** [comment]
Post battle replenish was fixed in Patch 4.1: "Fixed an issue where the Warriors of Chaos / Norsca Enslave Captives option would sometimes appear for other races post-battle, rather than just between the Warriors of Chaos and Norsca"
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b2595781-a093-4891-a88a-690c294d058a)
