### ISSUE TITLE
Mismatch between building name and short description text in marble resource chain

### ISSUE THREAD

**Issue by BobEngelbert** [chadvandy/cbfm_wh3#1417]
For most (if not all) factions, the name of tier 1 of the marble resource building chain references the short flavour text for tier 2, and vice versa

I expect the building that extracts marble from the ground to refer to the extraction of marble, and for the building that refines marble to refer to the refinement of marble.

1: Play as a faction that starts close to a marble region.
2: Conquer said marble region.
3: Hover over the marble resource building (tiers 1 and 2) and read the flavour text.

Personal opinion: It's the building names that are switched, not the flavour text.

Screenshots are from an Ice Court campaign occupying Praag in the Realms of Chaos map.

Based on what I find in local_en.pack, this issue is present for the following factions:

Bretonnia
Dark Elves
High Elves
Lizardmen
Skaven
Cathay
Kislev
Dwarfs
Empire

![Screenshot 2024-02-18 142110](https://github.com/chadvandy/cbfm_wh3/assets/146353701/163e1cff-275b-4b7b-8920-cae3625a7c80)
![Screenshot 2024-02-18 142346](https://github.com/chadvandy/cbfm_wh3/assets/146353701/a0d86fc1-d096-48fe-b7dc-8e111c860cd4)

**Comment by Grimmys** [comment]
Ok, I did some investigating... It's messy.

Descriptions (or rather, name of buildings) are indeed swapped for Marble I and II in loc file.

But looks like at some point they noticed it, and considered it too late to be fix, so instead, they just swapped the description keys in buildings table (`db/building_culture_variants_tables/data__`).
I.e., key for description of empire marble 1 is "wh_main_emp_resource_marble_**2**", and key for description of marble 2 is marble 1.
Same for some other factions, but it's a bit more complicated because they like reusing keys for different factions.
For Dark Elves, in order, it's key for description of High Elves Marble 2, Empire Marble 1, High Elves Marble 3, but since the order is "correct" (2, 1, 3), I guess everything is fine.
However, looks like they didn't remember they have to swap the order for every factions, hence the issue you noticed for Kislev, or the one I found for Lizardmen as well (keys are "Lizardmen Marble 1, Empire Marble 2, Lizardmen Marble 3").

So the issue is **not reproducible for all the factions you listed**, only some of them (like Kislev, Lizardmen and Skaven).
Still for the other ones (like Empire, High Elves etc.) the fix they chose is to invert the description keys, instead of the building names that would have been more coherent like you said.

At the end, I see two ways of approaching this issue:

- The proper one but harder: change in localization file all the building names for Marble 1 and 2 for every faction in **every language** supported by the game. Then in buildings table, correct the order of description keys for it to be always 1, 2, 3.
- The simpler one: ensure that in buildings table, the order of description keys is always 2, 1, 3, to take into consideration the mistake in localization file. Buildings would still be _Sawyer_ and then _Marble Quarry_, but descriptions would always be consistent with their building.

I'm open to work on the second approach if it's okay.
I feel like the first one would be too much of a pain for such little detail.

**Comment by Harmandodelavega** [comment]
Sorry for not following but for number 2 the bug would just be visible internally?

**Comment by Grimmys** [comment]
No worries, situation is tricky.
It would not be only "internal bug".

So in fact, current situation is:

```
Marble I: Sawyer - description of "Quarry"
Marble II: Quarry - description of "Sawyer"
```

For some faction.

Suggested fix by author's is:

```
Marble I: Quarry - description of "Quarry"
Marble II: Sawyer - description of "Sawyer"
```

It is what would make more sense.

What would my second approach do:

```
Marble I: Sawyer - description of "Sawyer"
Marble II: Quarry - description of "Quarry"
```

It is in fact what CA already did for a few factions like Empire and Elves factions.
So no inconsistency across buildings (each description match building name), but Sawyer would come before Quarry, what can sounds weird.

**Comment by Harmandodelavega** [comment]
Better than what we got
