### ISSUE TITLE
Constructs gets healed by corpse cart units

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1423]
https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/3351-grand-cathay-s-construct-get-healing-from-corpse-cart-unholy-lodestone-and-mortis-engine?page=1

**Comment by mfvreeland** [comment]
Interestingly, this looks like it's always been broken, but no one cared before because the only race that had units flagged as "Construct" was Tomb Kings, an otherwise completely undead race. There does not appear to be an ability invalidation flag available for "unit is construct" (only the opposite flag, "unit is not construct," exists), and it doesn't appear that custom flags can be made via modding (these seem to come straight from code) -- but perhaps scripting it so that the game considers constructs to be "living" would circumvent the issue without any negative side effects. I'll experiment.
