### ISSUE TITLE
Grudges abort or can't be completed if targeted factions are confederated

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1662]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1033-malakai-grudges-no-longer-appearing-completed?page=1

**Comment by sm0kin** [comment]
The mission_type "DESTROY_FACTION" (only used for scripted legendary grudges in the form of a mission_manager objective) aborts the grudge/mission if the last targeted faction is confederated instead of destroyed or bugs out the grudge (can't be finished) if any targeted faction is confederated.
I was made aware of the issue due to how my mod (RDLL) works, but the issue also happens in vanilla when a targeted faction is confederated via diplomatic action or culture specific mechanics (like Grn defeated leader dilemma etc.).
This can be easily reproduced by use of the force_confederation command during any Dwf campaign.

This is the function causing it.
`function legendary_grudges:setup_destroy_factions_mission_condition(mission_manager, target_faction_list, add_to_primary)
	local add_to_primary = add_to_primary or nil
	mission_manager:add_new_objective("DESTROY_FACTION", add_to_primary)
	for _,v in ipairs(target_faction_list) do
		mission_manager:add_condition("faction " .. v);
	end
end`

Changing the "setup_destroy_factions_mission_condition" to use a purely "SCRIPTED" objective similar to how the "setup_occupy_regions_mission_condition" works, but with listeners for both the "FactionDeath" and "FactionJoinsConfederation" event should fix the issue.

**Comment by floskan** [comment]
Might be something to look into if CA doesn't fix it. I REALLY need to learn lua

**Comment by mfvreeland** [comment]
I could do this in the way sm0kin described, and it would work, but I'd really rather CA just fix the code for the "DESTROY_FACTION" mission to be honest. It would be cleaner (and easier!). If they don't touch this in their first real patch for 5.0, I'll jump on this.

**Comment by Drazhir2** [comment]
Elegant solution found by Klissan: [zzz_cbfm_grudges_abort_fix.patch](https://github.com/chadvandy/cbfm_wh3/files/15417327/zzz_cbfm_grudges_abort_fix.patch) (rename to .pack)

**Comment by chadvandy** [comment]
5.1: "Fixed an issue where a Legendary Grudge could abort where the target faction was confederated"

**Comment by mfvreeland** [comment]
CA appears to have added Klissan's fix to the main script in 5.1. Assumed fixed unless reported otherwise.
