### ISSUE TITLE
WoC cannot get lore of slaanesh sorcerer from shadow sorcerer anymore 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1710]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1150-woc-cannot-get-lore-of-slaanesh-sorcerer-from-shadow-sorcerer-anymore?page=1

"to build on this error, background_character_initiative_sets_tables claims to allow 6 in the "amount to select" column, but despite this is still unable to show more than 3 options, even without mods. meanwhile the chaos lord is able to show all 5 options - devotion to each of the 4 gods and daemon prince ascension.

the images attached show i have the same issue as mister z (even when playing a different warriors of chaos faction), and show the table mentioned using the unnoficial modding tool "RPFM", with the relevant sorcerer hero line highlighted. additionally the images show that for chaos lords more than 3 options are visible."

**Comment by floskan** [comment]
@mfvreeland Do you have any ideas how to make this work?

**Comment by mfvreeland** [comment]
What's supposed to happen exactly? Which options should a Shadows sorcerer have?

**Comment by floskan** [comment]
They're missing the option to ascend so a slaanesh magic sorcerer, since there's only three options to choose between.

**Comment by mfvreeland** [comment]
So there's supposed to be four options total?

**Comment by floskan** [comment]
Yes, if I'm not missing anything obvious it should be 4 possible combinations when having a shadow sorcerer when playing undivided woc

**Comment by mfvreeland** [comment]
So here is what changed in 5.0:

![image](https://github.com/chadvandy/cbfm_wh3/assets/112144702/3c3d734c-d821-45d6-804b-be1bbd93b68e)

They swapped out devoting to Tzeentch (Tzeentch) and Slaanesh (Slaanesh) for Shadows/Death sorcerers in favor of the two Nurgle options (Nurgle and Death). We could just add Slaanesh back to this table (`initiative_set_items`), but then Shadows/Death sorcerers would four options whereas Fire/Metal sorcerers would have three. The trouble is there are no devoted sorcerers with a lore of fire, so that imbalances things. 

I am inclined to say that this imbalance doesn't matter, and it would be best to add Slaanesh back as an option for Shadows/Death sorcerers. Alternatively, we could separate it so that each sorcerer gets options as follows:

- Shadows: Slaanesh (Slaanesh) or Slaanesh (Shadows)
- Death: Nurgle (Nurgle) or Nurgle (Death)
- Metal: Tzeentch (Tzeentch) or Tzeentch (Metal)
- Fire: Slaanesh (Slaanesh) or Nurgle (Nurgle) or Tzeentch (Tzeentch)

Personally, I like this last option, but I also feel like it's a bit too much of a redesign for a bugfix mod.

Opinions requested.

**Comment by floskan** [comment]
I'm fine with whatever option, but i like the first one and i think it falls more under bug fix territory even if the second option makes more sense overall

**Comment by mfvreeland** [comment]
CA went a step further and just gave every option to every sorcerer type:

![image](https://github.com/chadvandy/cbfm_wh3/assets/112144702/53c9743e-8640-4147-ae98-a0d01615f4cf)

I guess that works, too!
