### ISSUE TITLE
Nurgle Units are recruited with reduced health as Daemons of Chaos faction 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1715]
"When recruiting Nurgle units as the Demon Prince, they start with reduced health."

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1116-nurgle-units-are-recruited-with-reduced-health-as-daemons-of-chaos-faction?page=1

**Comment by mfvreeland** [comment]
This doesn't happen.

**Comment by chadvandy** [comment]
5.1: Fixed an issue where sometimes the Daemon Prince would recruit Nurgle units not at full health

**Comment by mfvreeland** [comment]
I guess this did happen in weird circumstances, although I couldn't reproduce it even before 5.1. Assumed fixed unless it gets reported again.

**Comment by AphyriaCelosia** [comment]
I managed to figure out the steps to reproduce the bug prior to 5.1 (5.1 patch does appear to fix it!). Was bugging me, and this way we know in case something breaks in the future.

In order for it to happen, you need to;

1. Have a settlement in the same region as a Nurgle faction (can do this even without console turn 2 by taking Tower of Flies).
2. Recruit nurgle units
3. Nurgle units will start damaged (as if using the Nurgle faction mechanics related to recruitment).

This only appears to happen if the province is partially owned by a Nurgle faction, which made it difficult to reproduce - recruiting in Volcano's Heart was fine since it was shared with Tzeentch. 

![image](https://github.com/chadvandy/cbfm_wh3/assets/173944160/364acbf5-7e12-48c3-9d73-cf1734e24953)

**Comment by mfvreeland** [comment]
Mystery solved! Glad to have confirmation that 5.1 fixed the underlying issue.
