### ISSUE TITLE
 Dread Knights wrong armoured Cold One texture 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#1805]
"Cold One Dread Knights are using wrong texture on their mounts. They use unique texture of Spite, Malus Darkblade mount. That bug is since launch of Immortal Empires."

https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/1550-dread-knights-wrong-armoured-cold-one-texture?page=1

**Comment by Drazhir2** [comment]
"Cold One Dread Knights are using wrong texture on their mounts. They use unique texture of Spite, Malus Darkblade mount. That bug is since launch of Immortal Empires."

I must be blind, these don't look the same:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/39771c04-1d44-43ec-92f4-3de46a12d038)

All 3 textures regular/malus/ebon claw in order:
![cold_one](https://github.com/chadvandy/cbfm_wh3/assets/135981276/317c4571-75e0-43b0-930a-4f1784ba5a1b)

**Comment by mfvreeland** [comment]
Looks different to me.
