### ISSUE TITLE
Festus, nurgle-plague button never be activated after hotfix 5.0.4

### ISSUE THREAD

**Issue by jurgler** [chadvandy/cbfm_wh3#1853]
**Describe the bug**
When play as Festus, the nurgle-plague button never be activated despite gathering 200 more infection points.

**Expected behavior**
When playing new game as Festus  after hotfix 5.0.4,
I can't use plague because nurgler-plague button never be activated.

The Nurgle-Plague button tooltip shows that the infection score is stuck bellow 200 within  4 ~ 5 turns.
Despite collecting more infection points over several turns, it hasn't been updated since then.

If I disable this mode, it works well.

**To Reproduce**
1. cbfm mod enabled
2. New Play as Festus
3. Play until gathering infection score over 200 and play 6 or more turns
4. Experience crash/bug
The nurgle-plague button is not activated in campaign UI despite gathering 200 more infection scores

**Screenshots**
![festus_cbfm_bug_report_20240614](https://github.com/chadvandy/cbfm_wh3/assets/8564498/39d4c243-fc84-4cab-8bb6-40204dec8fc2)

**Comment by Drazhir2** [comment]
Confirmed script break from cbfm, the global var fix has been removed from github already but is still in the workshop version. Will be fixed with the next cbfm update.

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/871965bf-07bc-418a-bb98-f698ebcc935d)

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/4b9eba04-b300-4e97-aae6-58f88bc8e72a)

**Comment by mfvreeland** [comment]
This is an issue with CBFM that has been fixed internally (but not yet on the Steam version). We should be updating soon, but if you want to use a version without this problem in the meantime, use this (change .patch to .pack, place in data folder):

[zzz_cbfm_wh3.patch](https://github.com/user-attachments/files/15847616/zzz_cbfm_wh3.patch)
