### ISSUE TITLE
Lord recruitment cost bonus from Mannfred's 4th book of Nagash does not work when replacing lords

### ISSUE THREAD

**Issue by allenhu0912** [chadvandy/cbfm_wh3#2001]
![20241201125000_1](https://github.com/user-attachments/assets/9df1c927-e41f-4224-b5ae-216755185386)
![20241201125158_1](https://github.com/user-attachments/assets/4293610a-d7e3-4161-beb5-551331a60f01)

Compare lord recruitment costs

**Comment by mfvreeland** [comment]
It looks like CA did include a hidden force-scope effect to account for lord replacements when making this effect bundle, so it *should* be working just fine:

![image](https://github.com/user-attachments/assets/9548832e-5f67-479a-8cd3-2b5cc34a237d)

It's also not clear from the screenshots what the issue is... it looks like everyone available in both is rank 40.

**Comment by allenhu0912** [comment]
The recruitment rank is correct. But the recruitment cost is not, if you look at the Blood Dragon lords.

**Comment by mfvreeland** [comment]
Ah, my mistake. Yes, it does look like the hidden cost modifier for replacement lords is missing. Thanks for clearing that up.

**Comment by mfvreeland** [comment]
No longer relevant in 9.0, causing problems
