### ISSUE TITLE
Ogre Big Names Have Big Problems

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2108]
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5830-ogre-big-names-have-problems-conditionally-unlocking?page=1

Related to #2096:
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5808-the-big-name-magic-feaster-is-bugged?page=1

**Comment by mfvreeland** [comment]
The only bug I can confirm from looking at the script is that the "Magic Feaster" name will never proc for hero units because the script only checks the general. I don't see why the Daemon wins check wouldn't work, nor is there any reason why a Hunter would need to reach exactly rank 15 to meet the requirements for that Big Name (the script procs on rank up and will succeed on any rank equal to or greater than 15, so it's fine if 15 is skipped). It is true that none of these will proc for a reinforcing army, but that could be by design, so I don't think we should touch it. 

Fix for Magic Feaster incoming.

**Comment by mfvreeland** [comment]
To check tomorrow: "Butcher and Firebelly heroes should now receive the Big Name "Magic Feaster" when they complete the requirement to win a battle against a spellcaster character"
