### ISSUE TITLE
Crash when devoting a lvl 50 (mby lower) character having researched Champions of Chaos Dlc tech for+50% ranks kept after devoting (fix in comment)

### ISSUE THREAD

**Issue by KeepCalm321** [chadvandy/cbfm_wh3#226]
**Describe the bug**
When you have "Indisidious selection" tech researched and devote a lvl 50 character to khorne the game closes

**Expected behavior**
idk, anything but crash

**To Reproduce**
1. play as Valkia
2. research "Indisidious selection"
3. try do devote to khorne any of your lvl 50 (maybe lower than 50? but definitely higher than 20 I think) characters
4. Experience crash/bug

**Screenshots**
If applicable, add screenshots to help explain your problem. The more in-game text we can see to reference the details in question, the better.

**Saves**
If this is a hard-to-reproduce problem and you have a save game, please provide your save game! They are located in AppData/Roaming/The Creative Assembly/Warhammer3/save_games/

**Additional context**
It may be less than lvl50, my original save where I encountered the bug have mods, so I made the same thing with cheats to represent it in vanilla. Just choose hero in valkia's army and press the devotion button. 
[Gorequeen devotion bug.13610753859.save.zip](https://github.com/chadvandy/cbfm_wh3/files/9530232/Gorequeen.devotion.bug.13610753859.save.zip)

**Comment by jgammey** [comment]
This occurs with all of the techs for +50% ranks kept after devoting. So Insidious Selection for Valkia, Powerful Patients for Festus, Sensation's Call for Azazel, Summoning Rite for Vilitch.

The bug comes from wh3_campaign_character_upgrading.lua at line 392. When called at rank 50 with any of the above techs, it will try adding rank 51 experience to the new character.

Additionally, that function should probably use "math.ceil(old_char_details.rank * new_character_level_proportion)" instead of adding 1 at the end because the addition means that with those techs, the new character will be 1 rank higher than the original. This change would fix both bugs, I think.

**Comment by mfvreeland** [comment]
Is this still a bug? I can look into it at some point if so.

**Comment by jgammey** [comment]
I am unable to trigger the bug anymore. While the script appears unchanged, it seems CA has at least fixed when a script tries creating a character with rank >50.

**Comment by mfvreeland** [comment]
Apparently fixed by CA.
