### ISSUE TITLE
DEF lords can have multiple names of power traits

### ISSUE THREAD

**Issue by sm0kin** [chadvandy/cbfm_wh3#26]
Disbanding or replacing a DEF lord on the same turn you get a name of power skill triggers the dilemma again. Seem to happen for the ai's lords as well.

**Comment by zamioku** [comment]
+1
This also commonly happens when a lord with the "Immortal" trait is wounded in battle.

**Comment by mfvreeland** [comment]
I tried messing around with this one a bit today, but the fix is not readily apparent. I could script it so that if the dilemma comes up beyond the first time, whatever choice is made is nullified, leaving the lord with only his/her original name of power trait, but this still leaves the awkward situation of the dilemma potentially showing up multiple times to begin with. There is a way using the CampaignUI object to force close the dilemma window that comes up, but unfortunately, the UI seems locked until a choice is made, so closing that window just leaves it locked. There may be some UI tricks around this I just don't know about, however.

**Comment by mfvreeland** [comment]
Update: Still broken in 2.2

**Comment by mfvreeland** [comment]
Update: Still broken in 2.3

**Comment by Harmandodelavega** [comment]
Does it still need testing?

**Comment by mfvreeland** [comment]
My fix still appears to work just fine in 2.3, although it hasn't been code reviewed by anyone nor has it been tested in multiplayer. I don't anticipate any problems, but you never know. On the other hand, it should be easy enough to revert in case anyone does come across e.g. a multiplayer sync issue.

**Comment by mfvreeland** [comment]
Update: Still broken in 2.4. I have updated my fix to me compatible with MP, though. Testing now, will update shortly.

**Comment by mfvreeland** [comment]
This was apparently fixed properly in 3.0. Once confirmed, this band-aid will be removed.

**Comment by mfvreeland** [comment]
Confirmed fixed, removing from CBFM.
