### ISSUE TITLE
Grom and Drycha enemy morale debuff when fighting Elves skill doesn't work (Mandras)

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#292]
Originally by Mandras

https://cdn.discordapp.com/attachments/581350140942483456/1019249381234454598/Grom_Mandras.pack

**Comment by Layotees** [comment]
![image](https://user-images.githubusercontent.com/113050609/194616417-bda40a63-7966-41e5-8cb1-565cc45e112c.png)
![image](https://user-images.githubusercontent.com/113050609/194616465-89c58f1e-efc4-4bf0-b6e1-3538c661c267.png)
Works for Grom, doesn't look like it's working for Drycha, but unsure based on comments if the fix is implemented for Drycha yet.

**Comment by Harmandodelavega** [comment]
It is implemented, weird

**Comment by Layotees** [comment]
Drycha's is -8 vs Grom's -7.  Loaded up Drycha again, initially when I tested her it was against Laurelorn WE, no effect.  Trying it against HE now for consistency with Grom.
![image](https://user-images.githubusercontent.com/113050609/194648314-9ece520b-0a3b-4d90-9648-23dffb01ba10.png)
No change.
![image](https://user-images.githubusercontent.com/113050609/194648362-10048c19-3a06-46fc-8db5-5eb2b84aa87a.png)

**Comment by Harmandodelavega** [comment]
mby it just works in battle? thx anyways

**Comment by Harmandodelavega** [comment]
The updating is really wonky, but when you start a fight it shows in the battle preview screen and stays should you retreat. I haven't throroughly tested all the campaign updating and whether the local region is actually precise but it working in battle is enough
