### ISSUE TITLE
Ratnik SpiderClaw doesn't affect spider RoR

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#299]
Originally by Mandras

**Comment by floskan** [comment]
Was about to make a pull request for this, but it looks you might have a fix in your fork? Could you please make a pull request for things you already fixed so i know what i can ignore? 👍

**Comment by Harmandodelavega** [comment]
Yes should be just adding the RoRs to the spider set

**Comment by greendam** [comment]
The Spider Rider Archer RoR not only missing from spider set but also goblin set, its normal counterpart gets all goblin buffs and SpiderClaw's buff while the ROR gets neither. 
Lava Spider Rider Archer from Call to WAAAGH doesn't affected by Grom's Cauldron buff to Goblin archers, while Forest Goblin Spider Rider Archer does.
Since you are fixing the Spider RoR here, maybe you can include them as well please

**Comment by Harmandodelavega** [comment]
> The Spider Rider Archer RoR not only missing from spider set but also goblin set, its normal counterpart gets all goblin buffs and SpiderClaw's buff while the ROR gets neither. Lava Spider Rider Archer from Call to WAAAGH doesn't affected by Grom's Cauldron buff to Goblin archers, while Forest Goblin Spider Rider Archer does. Since you are fixing the Spider RoR here, maybe you can include them as well please

I'll check this out

**Comment by Harmandodelavega** [comment]
> The Spider Rider Archer RoR not only missing from spider set but also goblin set, its normal counterpart gets all goblin buffs and SpiderClaw's buff while the ROR gets neither. Lava Spider Rider Archer from Call to WAAAGH doesn't affected by Grom's Cauldron buff to Goblin archers, while Forest Goblin Spider Rider Archer does. Since you are fixing the Spider RoR here, maybe you can include them as well please

All but the Grom bug were already fixed
