### ISSUE TITLE
Most Flesh Laboratory upgrades not working (Clan Moulder/Throt)

### ISSUE THREAD

**Issue by Pterosquirrel** [chadvandy/cbfm_wh3#451]
Most of the upgrades in the Flesh Lab currently have no effect when purchased. See list below. Issues with earlier upgrades should be easy to reproduce.

WORKING:
- Genetic Filtering (+3 recruit rank)
- Bio-Recycle Chamber (+5% mutagen from battles)
- Abnormal Growth Cultivation (+Food per batch)

NOT WORKING (no effect from upgrade)
- Clone Warfare (Random mutations on Skavenslaves)
- Deep Freezer (Increased Mutagen limit)
- Abnormal Growth Cultivation (Food for recycling, additional augments)
- Mutagen Distillation (reduced upkeep for instabilities)
- Steroid Infusions (ward save for 4+ augments)

LIKELY NOT WORKING
- Enlarged Growth Vat (more units per batch)

Last one was hard to test due to RNG elements involved in unit generation, but I was eventually able to get matching batches both with and without the upgrade.

**Comment by Mandras2** [comment]
The Flesh Lab script has a listener that stores a boolean value in a table whenever the player purchases a Flesh Lab upgrade. Every function that checks this table to see if you have the upgrade fails to work. Something is wrong with the syntax of thetable or the way other functions reference it, because, if you simply comment out all conditions for "wh2_dlc16_throt_flesh_lab_upgrade_" everything labled as "NOT WORKING" here will be available and working on turn one. I modified the script to use separate listener's for each upgrade and use simple variables instead of a table and it works. Maybe someone with more LUA knowledge can actually fix the original table or the listener.

[!_MOD_skv_flesh_lab_fix.zip](https://github.com/chadvandy/cbfm_wh3/files/9724262/_MOD_skv_flesh_lab_fix.zip)

**Comment by Mandras2** [comment]
Did some additional testing and fixed a problem with the ward save from Steroid Infusions applying to units incorrectly.
The only issue remaining is the one free augment (or 2 Abnormal Growth Cultivation) you get when recruiting through the flesh lab will stop working eventually.  Haven't been able to figure out why that is.

[!_MOD_skv_flesh_lab_fix_v2.zip](https://github.com/chadvandy/cbfm_wh3/files/9739494/_MOD_skv_flesh_lab_fix_v2.zip)

**Comment by mfvreeland** [comment]
Fixed by CA in 2.2, should be removed
