### ISSUE TITLE
Nurgle cult building stops working in max surplus provinces

### ISSUE THREAD

**Issue by Sable-Drake** [chadvandy/cbfm_wh3#71]
will it work for Chorfs or Welves since no Growth/Kindreds?
Editor's note: Uses GrowthGreaterThan200 rather than GrowthGreaterThan200DPare5 in building effect junctions- context requirements

The former merely checks growth, the latter also checks for 5 development points, so it will not stop working. Nurgle temple buildings use the latter.

**Comment by Sensang** [comment]
I was wondering.. what are development points? I was assuming it means surplus in which case I can confirm: There is no increased income for when you reach the threshold in surplus. If this gets fixed please rename it to surplus, because development points is not used anywhere else in the game.

**Comment by Harmandodelavega** [comment]
From the bug report

"Nurgle minor settlement building is supposed to provide additional income when growth is above 200 is not providing it. I checked all the economy statistics and it was infact not giving the income so it wasn't a visual bug. It did provide the bonus income when growth was below 200 so perhaps a the bug lies in incorrect code input. Screenshot included "

**Comment by Harmandodelavega** [comment]
I get it, the entry in building effect junctions for cults has the wrong context requirement

**Comment by mfvreeland** [comment]
Is this fixable?

**Comment by Harmandodelavega** [comment]
just need to change the additional context requirement for cult buildings and see if they work in a 5 surplus region

**Comment by mfvreeland** [comment]
@Harmandodelavega Was this ever included in any pull request? Just doing some spring cleaning of old issues today.
