### ISSUE TITLE
Dwarf unit runes equippable on characters

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#745]

**Comment by mfvreeland** [comment]
It turns out this doesn't fix the issue because you can assign multiple unit sets to a single banner. The only way to fix this seems to be via datacore, which is too sinful to consider. I'll reopen this in case anyone can come up with a better solution, but for now I think this can't be fixed by us.

**Comment by chadvandy** [comment]
5.1, "Dwarf banner runes from the forge are now applied to units only, as the text tooltip indicates."

**Comment by AphyriaCelosia** [comment]
![image](https://github.com/chadvandy/cbfm_wh3/assets/173944160/6692ade9-6d76-4c0f-b26a-734b0385f35c)

The equipping on characters part does seem fixed (greyed out, can't add to them). Tested 2 different banner types

**Comment by mfvreeland** [comment]
Fixed in 5.1
