### ISSUE TITLE
Huntsmen general anti-large projectile upgrade bugged

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#799]
Character skill junc was zeroed out
Archers linked to crossbows
Huntsmen not sure what they should be getting

**Comment by floskan** [comment]
> Character skill junc was zeroed out Archers linked to crossbows Huntsmen not sure what they should be getting

Hey @Harmandodelavega , do you want me to put up your fixes that needs testing that includes this, or should i just make a separate pr for this?

**Comment by Harmandodelavega** [comment]
4.2 edit: They just activated the ability without fixing it

**Comment by LilIronWall** [comment]
They patched it wrong in 5.0.3, from the patch notes: "Fixed an issue where the Huntsman General's "Experienced Hunter" skill was giving regular empire archers upgraded crossbow bolts from crossbowmen instead of upgraded arrows."

It doesn't give crossbow bolts to the archers anymore. However, it just stopped giving the bonus vs. Large for archers. It does increase their range. From my testing Huntsmen receive all the bonuses correctly (range and +8 bonus vs Large)

**Comment by Drazhir2** [comment]
Somehow they missed some tables, the missile weapon for the regular archer upgrade doesn't exist nor does the projectile itself:

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/5d8c8b9a-3304-40b7-b9a8-b0ca8de36519)

Very surprised it doesn't cause issues, if they had rpfm diagnostics they would've seen this:

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/597e326d-7332-4bbc-83e0-641c86611434)

**Comment by LilIronWall** [comment]
That's some proper bug fixing philosophy, if it doesn't work just remove it. It can't be broken if it doesn't exist!
Nice plug for RPFM, it's surprising that they don't have an equivalent diagnostics tool. And if they don't they could just use RPFM...

**Comment by floskan** [comment]
Okay, keeping our fix should just work then I guess?

**Comment by Drazhir2** [comment]
yes, if you want to nitpick the wh2_dlc13_emp_bow_arrow_anti_large entry can be removed from projectiles, it's not used by vanilla nor by CBFM where we have our own replacement projectiles.
