### ISSUE TITLE
Imrik dragon encounter crash + Generic dragon encounters not working/Giving the appropriate reward

### ISSUE THREAD

**Issue by LordOmlette** [chadvandy/cbfm_wh3#826]
1. When doing a dragon encounter, the game could randomly crash upon completion.
2. The first generic dragon encounter will fire fine and subsequent ones won't.

Dragon encounters are rare, the crashes themselves, and generic dragon encounters don't happen until all 5 special dragons are collected, so this may be why no one's noticed.

**Comment by LordOmlette** [comment]
I'm using the following to fix the problem in one of my mods. 
[imrik_fixes_cbf.lua.txt](https://github.com/chadvandy/cbfm_wh3/files/10316414/imrik_fixes_cbf.lua.txt)

**Comment by floskan** [comment]
> I'm using the following to fix the problem in one of my mods. [imrik_fixes_cbf.lua.txt](https://github.com/chadvandy/cbfm_wh3/files/10316414/imrik_fixes_cbf.lua.txt)

What mod is that?

**Comment by floskan** [comment]
> 

I see, thank you. Would grabbing that script and put it under script/campaign in a standalone pack work just as well?

**Comment by LordOmlette** [comment]
Yes, it should work just fine, that script is just bug fixes and nothing else.

**Comment by floskan** [comment]
Hey @LordOmlette , is this still something that needs fixing? Can we grab the script from your mod in that case?

**Comment by Drazhir2** [comment]
Looks at least partially fixed.

From LordOmlette's script:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/a4f04cb7-ce02-42bf-8514-1b8a9ed8c508)

Full diff of the vanilla script since IE:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/e1dbe60c-3efc-445c-a4e5-428e8a8b8671)

Patch 3.0.0 (April 13th 2023) says "Fixed issues with Imrik’s dragon encounters not triggering after completing the five named dragon encounters."

**Comment by LordOmlette** [comment]
Hi, sorry, once again I forgot to update here.  Like Drazhir said, it looks like CA addressed this in vanilla so I think we can close this.
