### ISSUE TITLE
Gotrek's Heroic Fortitude not working 

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#870]
(https://www.youtube.com/watch?v=YzE8aNPRz_g&t=573s)](https://www.youtube.com/watch?v=YzE8aNPRz_g&t=573s)

https://github.com/chadvandy/cbfm_wh3/issues/655

**Comment by aimop95** [comment]
I have a fix, but I'm not sure how to exactly go about putting it in?

**Comment by Harmandodelavega** [comment]
If you have a pack drop it in the community bug fix discord channel, I can't tell you when it will be added though

**Comment by aimop95** [comment]
Would you happen to have the link? I can't find it on github.

**Comment by floskan** [comment]
> 

https://discord.gg/moddingden

**Comment by aimop95** [comment]
Here is the .pack file that fixes Gotrek's heal. 
[Gotrek_Heal_Fixed.zip](https://github.com/chadvandy/cbfm_wh3/files/11010222/Gotrek_Heal_Fixed.zip)

**Comment by mfvreeland** [comment]
This ability works. It's just very minor (only heals 12% of Gotrek's HP pool), and the heal is oddly tied to its miscast phase rather than the normal phase. Because the miscast chance is 50/50, though, this arrangement doesn't really make any difference.  The ability could probably be retuned to have more of an impact (for comparison, the High Elf phoenix "rebirth" ability that does basically the same thing heals twice as much at 25%), but balance changes like that are beyond the scope of CBFM.
